name: issue comment test
on:
  issues:
    type:
      - labeled

jobs:
  test-comment:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write
    steps:
      - name: Output files
        id: json_out
        run: cat data.json
      - name: Comment on Issue by github-script
        uses: actions/github-script@v6.3.3
        env:
          DATA: "json\n${{ steps.json_out.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `
            \`\`\`
            ${process.env.DATA}
            \`\`\``;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
